### ISSUE TITLE
Launch storyboard images does not resize properly in IOS

### ISSUE THREAD

**Issue by shashankdevp** [apache/cordova-plugin-splashscreen#156]
In my application recently I moved from Legacy Start Screen images to Launch storyboard images. Here after moving to the new story board images type in IOS, while rendering Splash screen on the device the image gets cropped off. If it works for one type of device, it may not work for another. 

ex: I had issue in IPhoneX when I resized the image and rendered on the device it worked but started getting same issue in IPhone 6s.

**Comment by pipoec** [comment]
I have the same issue have you tried looking the version of the cordova plugin?

**Comment by ppetree** [comment]
I have the same issue BUT MORE IMPORTANTLY, why in the hell are they trying to convert my legacy splashscreens to launch images?  (This is another stupid, cordova self-inflicted issue!)

**Comment by RTK** [comment]
I agree to this topic and think the way this plugin handles storyboards is not optimal. Since storyboards are more complex than adding a simple image that should fit anywhere.

If you have the possibility and check out storyboards in XCode you will see, that you can create storyboards with constraints, containing of multiple images, etc.

My current solution is, that I created a custom storyboard and then use a hook to overwrite the default Cordova storyboard.

**Comment by jcesarmobile** [comment]
The plugin has been integrated into cordova-ios 6, so no more iOS work will be done here.
If there are still bugs on the cordova-ios 6 implementation, report them on https://github.com/apache/cordova-ios/issues
