### ISSUE TITLE
Splash screen images for iPhone XR, iPhone XS, and iPhone XSMAX

### ISSUE THREAD

**Issue by sdgpalm2** [apache/cordova-plugin-splashscreen#158]
Code updated to support "Splash screen images for iPhone XR, iPhone XS and iPhone XSMAX", files attached, just expanded on the above code. iPhone XS uses iPhone X code, iPhone XR and iPhone XSMAX uses same limit of limit == 896. New to all this GitHub stuff, contributing openly.

Yes I would be interested in learning to fork and submit this in a proper PR, thanks! 

[CDVSplashScreen_h.txt](https://github.com/apache/cordova-plugin-splashscreen/files/2407633/CDVSplashScreen_h.txt)
[CDVSplashScreen_m.txt](https://github.com/apache/cordova-plugin-splashscreen/files/2407634/CDVSplashScreen_m.txt)

See pull #159

**Comment by janpio** [comment]
Awesome.

So what you want to do is create a Pull Request (PR) from a branch in a fork of this repository where you changed those files.

Small glossary:
- Pull Request = Like an issue, but has code attached to it that can simply be merged into the original repository
- Branch = A "branch" in a repository with some changes. There mostly is a `master` branch that has the main code, and many other branches with slight modifications. That way you can have a branch for each bug, feature etc. and it is easy to see only the changes for that
- Fork = Copy of a repository under your username. At first a fork is just a copy, but then you can make changes in there (you can't do that here because you don't have access) and send a PR with those changes later.

Now some links with instructions what you have to do:
1. Fork the repo: https://help.github.com/articles/fork-a-repo/ Really relevant is just this bit: https://help.github.com/articles/fork-a-repo/#fork-an-example-repository
2. Make changes in your repository: Now you can check out your fork with Git to your computer, change the files and commit and push the changes: https://help.github.com/articles/cloning-a-repository/ + https://help.github.com/articles/adding-a-file-to-a-repository-using-the-command-line/
Or you can do it online on Github.com in the UI: https://help.github.com/articles/editing-files-in-your-repository/
3. When you have edited both files in your fork, you can create a pull request on this repository to get your changes back here: https://help.github.com/articles/creating-a-pull-request/
4. Then we have a Pull Request here with your changes that we can look at.

This seems like _a lot_ now, but it is just a few simple steps once you understood it. Let me know if you hit any stumbling blocks, I'll be happy to help you along the way.

**Comment by sdgpalm2** [comment]
I might need some help:
I performed a fork, made changes to the files in the fork that showed up in my GitHub account and from within my account at the completion of the edits created Pull Request, but if I go into https://github.com/apache/cordova-plugin-splashscreen/pulls <https://github.com/apache/cordova-plugin-splashscreen/pulls> I’m not seeing the Pull Request show up??

**Comment by janpio** [comment]
Common misunderstanding: You are creating the pull requests from the branch in your fork to `master` in your fork. They show up here: https://github.com/sdgpalm2/cordova-plugin-splashscreen/pulls You have to create the Pull Request to this repository, for example by creating the PR here: https://github.com/apache/cordova-plugin-splashscreen/compare

As I saw your two PRs, I noticed you edited the files in two different branches - sdgpalm2-patch-1 and sdgpalm2-patch-2 - which means you also need two PRs to get all the changes in. This should not be the case, you should try to edit both files in the same branch. You can do that by either going to one of the branches in your repository and also edit the other file, or create a Pull Request from one branch to the other, merge it and then merge _that_ branch into the Cordova repository.

Let me know if this works.

**Comment by sdgpalm2** [comment]
It’s now showing up as a Pull request,  is there anything else to do?

**Comment by janpio** [comment]
Not really, congratulations on your first PR! 🥇 💯 

You can add `closes #158` in the description field, then it will automatically close this issue when it is merged.

Now someone from the Apache Cordova team will have to look at, review and then merge it.

**Comment by Stefano1964** [comment]
iPhone XsMax and iPhone Xr have the same height in points (896) but not in pixel (2688, 1792 pixels), the launch images are not the same size in xcassets, there are distinct images for XsMax and Xr launch screen, you have to got with native screen bounds...
[CDVSplashScreen.zip](https://github.com/apache/cordova-plugin-splashscreen/files/2411613/CDVSplashScreen.zip)

**Comment by janpio** [comment]
@Stefano1964, can you follow the same steps I posted above to create a PR please?

**Comment by Stefano1964** [comment]
This is my own version, i do not fork @sdgpalm2...

**Comment by janpio** [comment]
Exactly, a new PR for the changes you made so they can possibly be integrated back into this plugin.

**Comment by sdgpalm2** [comment]
Pull #159 has been updated with code provided from @Stefano1964

**Comment by Stefano1964** [comment]
@sdgpalm2 thanks, i'm really busy in this days.
Also note that if you are editing an existing project in Xcode 10 the launch image for XsMax and Xr dont show up, you have to delete and recreate launch image xcassets:
https://stackoverflow.com/questions/52402062/iphone-xs-max-xr-not-able-to-use-native-resolution-when-using-launch-images-in

**Comment by sdgpalm2** [comment]
@Stefano1964, I've been using Asset Catalog Creator and did remove and replaced the xcassets, I even cleared the apps from the simulators and all the graphics did show up for me, but anyways, after reading your code, thought your process was correct, part of testing of your code yesterday was to edit the three images and place the works "X XS", "XR", "XSMax" into their respected selfs and did verified that they did show up correctly at launch based on the selected Xcode simulator, Thanks again!

**Comment by sdgpalm2** [comment]
@Stefano1964, code has beed code applied.

**Comment by Manaspaul623** [comment]
> Hi, iPhone XsMax and iPhone Xr have the same height in points (896) but not in pixels (2688, 1792 pixels), the launch images are not the same size in xcassets, there are distinct images for XsMax and Xr launch screen, you have to go with native screen bounds to detect the right iPhone model...
> [CDVSplashScreen.zip](https://github.com/apache/cordova-plugin-splashscreen/files/2411613/CDVSplashScreen.zip)

Not Working in  cordova 9.0 and ios5.0 version .

**Comment by jcesarmobile** [comment]
The plugin has been integrated into cordova-ios 6, so no more iOS work will be done here. 
Also, it now uses the launch storyboards, so this shouldn't be an issue anymore.
If there are still other bugs on the cordova-ios 6 implementation, report them on https://github.com/apache/cordova-ios/issues
