### ISSUE TITLE
issue on Samsung s9 plus.

### ISSUE THREAD

**Issue by daghass** [apache/cordova-plugin-splashscreen#165]
when adding this plugin version 5.0.2 to my application, it crashes on samsung s9 plus even when it is working on other devices such as samsung s9 and samsung note 8 with the same android version 8.0.

**Comment by jachstet-sea** [comment]
Do you see any stack trace in the device's log?

**Comment by swarzech** [comment]
I am having this issue on other devices as well

**Comment by jachstet-sea** [comment]
We had a problem displaying a 1920x1080 NinePatch on an S) and resolved is by reducing the image's resolution to 1280x768. Could be your problem as well, could be something different since both of you don't name whether you display a static image or a NinePatch and you don't provide any stack traces

**Comment by milankragujevic** [comment]
Same problem on Samsung A5, solved it by resizing the image to 1280x720/720x1280 respectively.

**Comment by adipascu** [comment]
I am also facing this error.
Here is more information about it and how to fix it:
https://stackoverflow.com/questions/44919245/error-runtimeexception-at-displaylistcanvas-throwifcannotdraw
