### ISSUE TITLE
iphone X using 3x~universal~comany.png for both landscape and portrait 

### ISSUE THREAD

**Issue by joeldhenry** [apache/cordova-plugin-splashscreen#195]
Has anyone seen this problem? `3x~universal~comany.png` works perfectly in portrait, but when flipped to landscape, app is still started with  `3x~universal~comany.png` instead of using `3x~universal~anycom.png`

device: iphone X
ios: 12.2.1
cordova cli 7.1.0
cordova-ios 4.5.5

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by janpio** [comment]
Can you share your `config.xml` you are using for this? Maybe there is something wrong. 

Have you also tried with a newer `cordova-ios` and Cordova CLI? There are newer versions available that might have fixes for this.

**Comment by jcesarmobile** [comment]
closing since there was no response

Also, the plugin has been integrated into cordova-ios 6, so no more iOS work will be done here and it now uses the launch storyboards, so this shouldn't be an issue anymore.
If there are still other bugs on the cordova-ios 6 implementation, report them on https://github.com/apache/cordova-ios/issues
