### ISSUE TITLE
AutoHideSplashScreen "false" not working on first launch on Android

### ISSUE THREAD

**Issue by drewrygh** [apache/cordova-plugin-splashscreen#217]
# Bug Report

## Problem

Setting AutoHideSplashScreen to false has no effect on the first launch of the app on Android. With subsequent attempts to open the app, the configuration works as expected.

### What is expected to happen?

When I open an app for the first time after installation on Android, and AutoHideSplashScreen is set to false, I'd expect that the splash screen is not hidden automatically.

### What does actually happen?

When I open an app for the first time after installation on Android, and AutoHideSplashScreen is set to false, the splash screen is hidden automatically (before any calls to manually hide the splash screen are made.)

### Environment, Platform, Device

Android — seems to happen on all devices, all Android versions.

### Version information

```
Ionic:

   ionic (Ionic CLI) : 4.2.1
   Ionic Framework   : ionic1 1.3.5
   @ionic/v1-toolkit : 1.0.19

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 7.1.4, ios 4.5.5
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 1.2.1, (and 40 other plugins)

System:

   Android SDK Tools : 26.1.1
   ios-deploy        : 1.9.4
   ios-sim           : 6.1.2
   NodeJS            : v11.0.0
   npm               : 6.4.1
   OS                : macOS
   Xcode             : Xcode 10.2.1 Build version 10E1001
```

## Checklist

- [x] I searched for existing GitHub issues
- [ ] I updated all Cordova tooling to most recent version **Not able to do this at this time.**
- [x] I included all the necessary information above

**Comment by janpio** [comment]
Is this reproducible in a new, plain Cordova app? A minimal reproduction repository would really help to debug and later fix this issue. More information on how to create one: https://github.com/apache/cordova-contribute/blob/master/create-reproduction.md

**Comment by drewrygh** [comment]
@janpio Thanks for the response, I'll try to set one up later today, and will post it here.

**Comment by drewrygh** [comment]
Sorry for the delay, I haven't yet been able to reproduce this yet in a plain Cordova app. I haven't played around with Cordova/plugin versions too extensively yet, nor the splash screen configuration, so it's likely related to one of these things — or something Ionic is doing.

If anyone else is having this issue and is able to look into reproducing this in a plain Cordova app, it'd be greatly appreciated. If I have time, I'll continue to try to reproduce this, but I can't guarantee I'll get to it soon.

**Comment by caleb87** [comment]
Did you get this working? I'm having the same issue. I've removed the whole platform and added again multiple times with different settings, and nothing has worked. I've tried putting SplashScreenDelay to 10s, but it still hides as soon as it opens and the app is still loading. AutoHide doesn't work. It seems like something else is overriding it. 

One thing that "works" is to show it immediately at deviceready, and then hide it when ready. It looks fine on the devices I have tested, but on others I hope it doesn't "flash" by doing this.

`navigator.splashscreen.show();`

**Comment by CodeWithOz** [comment]
@caleb87 @drewrygh did you both fix this in a more reliable way? `navigator.splashscreen.show()` is not working consistently for me.

**Comment by CodeWithOz** [comment]
@caleb87 @drewrygh do you have any hooks that edit your `config.xml` file? I created a sample app and the splashscreen works properly there (you can see [here](https://github.com/CodeWithOz/cordova-bad-web-workers/actions/runs/195501951)) so I'm suspecting that either one of my hooks or other installed plugin(s) is overwriting some of the settings in `config.xml`, since the splashscreen plugin defaults `AutoHideSplashScreen` to `true`.

**Comment by CodeWithOz** [comment]
@janpio hey I'm considering how to deactivate the auto-hide functionality right from the native code because the splashscreen still automatically hides when I set `AutoHideSplashScreen` to `"false"` in `config.xml`. I forked this repo and tried:
- changing [this line](https://github.com/apache/cordova-plugin-splashscreen/blob/f41610c2f7850b82325f0b35decbbcd6008a99cc/src/android/SplashScreen.java#L112) from
```js
boolean autoHide = preferences.getBoolean("AutoHideSplashScreen", true);
```
to
```js
boolean autoHide = false;
```
This didn't work (the splashscreen still hides automatically).

- commenting out [this line](https://github.com/apache/cordova-plugin-splashscreen/blob/f41610c2f7850b82325f0b35decbbcd6008a99cc/src/android/SplashScreen.java#L337). This also didn't work.

What else can I try or am I missing something? I have tried creating a simple reproduction (see my comment above) but the plugin works as expected there. Thanks!

**Comment by onthez** [comment]
Okay, so it's not just me. I've been working on my first Cordova app and figured I was doing something wrong but the splash screen keeps auto hiding immediately.  I implemented the suggested `navigator.splashscreen.show()` for now and that will have to suffice.

**Comment by CodeWithOz** [comment]
The culprit plugin for me was the background-geolocation plugin. I posted about this problem [there](https://github.com/transistorsoft/cordova-background-geolocation-lt/issues/1176). @onthez @caleb87 @drewrygh does any of you use that plugin?
