### ISSUE TITLE
Getting blank white screen when using Single storyboard image on Iphone X 11.0.1 simulator 

### ISSUE THREAD

**Issue by manusis** [apache/cordova-plugin-splashscreen#231]
# Bug Report
Getting blank white screen when using Single storyboard image on Iphone X 11.0.1 simulator 

## Problem
I tried specifying a single storyboard image with dimensions 2732x2732 in the config.xml of my phonegap app. It shows white screen instead of splash. The app opens properly after white screen. If I use multiple legacy splash images, then the splash image shows fine.

### What is expected to happen?

I should see the full size splash screen

### What does actually happen?
I see the blank white screen

### Command or Code

 ```
<platform name='ios'>
        <splash src='splash/ios/Default@2x~universal~anyany.png' width='2732' height='2732'/>
</platform>
```

### Environment, Platform, Device

Mac OS Iphone X Simulator 11.0.1

### Version information

Phonegap version: 8.1.1
cordova-plugin-splashscreen: 5.0.3

## Checklist

- [x ] I searched for existing GitHub issues
- [x ] I updated all Cordova tooling to most recent version
- [ x] I included all the necessary information above

**Comment by dyue** [comment]
Try and not specify width and height.

**Comment by DRK1004** [comment]
Even I have observed this on some devices like iphone6 (even with the sample Cordova App). Seems single splash screen is not working. You might have to provide minimum 6 images like:
    <splash src="res/screen/ios/Default@2x~universal~anyany.png" />
    <splash src="res/screen/ios/Default@2x~universal~comany.png" />
    <splash src="res/screen/ios/Default@2x~universal~comcom.png" />
    <splash src="res/screen/ios/Default@3x~universal~anyany.png" />
    <splash src="res/screen/ios/Default@3x~universal~anycom.png" />
    <splash src="res/screen/ios/Default@3x~universal~comany.png" />
Be sure to test on all devices as in my case this worked on iPhone 6 but it created new issue on other devices. On few devices splash screen was resizing or readjusting automatically. To resolve this I finally have to remove universal version of images and add images based on device type like:
<splash src="res/screen/ios/Default@2x~iphone~anyany.png" />
<splash src="res/screen/ios/Default@3x~iphone~anyany.png" />
<splash src="res/screen/ios/Default@2x~ipad~anyany.png" />

I am still investigating the root cause for resizing of splash screen but could not make whether it is from Apple or from Splash screen plugin (plugin method updateBounds is called twice) .

**Comment by jcesarmobile** [comment]
the plugin has been integrated into cordova-ios 6, so no more iOS work will be done here.
If there are still bugs on the cordova-ios 6 implementation, report them on https://github.com/apache/cordova-ios/issues
