### ISSUE TITLE
Feature request: Add additional check if splashscreen currently active

### ISSUE THREAD

**Issue by WuglyakBolgoink** [apache/cordova-plugin-splashscreen#240]
# Feature Request

## Motivation Behind Feature

because sometimes I need to do 2 actions which depends on status of splashscreen.

example:
1. I started App with autoHide splashscreen = false
2. prepare all data in first start via a lot of promises
3. render in background login page
4. hide splashscreen with timeout 2s after all promises was finished
5. show touch-ID dialog if available

then:

user logged in -> logged out
1. user will be redirected to login page again
2. login page will be again initialized and again called `navigator.splashscreen.hide()` with timeout=2s and then show touchId dialog

and in this case, this is not necessary to wait 2 seconds... I think...

## Feature Description

It will be great to have one additional check, if splashscreen currently active. Something like:
1. `navigator.splashscreen.isActive = () => boolean`
2. `navigator.splashscreen.isHidden = () => boolean`

**Comment by erisu** [comment]
I think we can close this request as not planned. 

Here's my reasoning:

It is preferred to implement an additional loading screen at the app-level. 

This might even be considered the best solution due to platform-specific behavior. 

Delaying the Splash Screen for an extended period can result in the app being perceived as unresponsive.

In the Android platform, for example, a significant delay will trigger an increased [ANRs (Application Not Responding)](https://developer.android.com/topic/performance/vitals/anr) reporting. 

Example ANR Issue Ticket: https://github.com/apache/cordova-android/issues/1510

Each platform may handle unresponsive apps differently, but I think the idea of not blocking the native UI rendering thread is important.

Implementing at the app-level would resolve such an issue.

Example Alternative Steps:

1. Allow the Splash Screen to hide automatically or introduce a slight delay of around a second or two, avoiding long delays that could trigger ANRs.
2. Display a loading screen or a visually similar design to the Splash Screen while the app fetches data or prepares to render the next screen.
3. Hide the loading screen once the app finishes loading and is ready to display its content.

If you feel the feature is still valid, please let us know but keep in mind about the complications of blocking the thread and unresponsive triggers. This is something that needs to be prevented.

Additionally, this plugin only supports the Browser platform now.

The Splash Screen feature is integrated into the core of Cordova Android and Cordova iOS.
