### ISSUE TITLE
iOS splash screen loader not showing

### ISSUE THREAD

**Issue by sufian1985** [apache/cordova-plugin-splashscreen#308]
# Bug Report
iOS splash screen loader not showing
## Problem
When i run my ionic app the loader is not working for iOS
### What is expected to happen?
iOS loader should show while splash screen is showing

### What does actually happen?
No loader shows

### Environment, Platform, Device

Ionic

### Version information
Ionic:

   Ionic CLI                     : 6.13.1 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.4.4
   @angular-devkit/build-angular : 0.1002.0
   @angular-devkit/schematics    : 10.0.8
   @angular/cli                  : 10.0.8
   @ionic/angular-toolkit        : 2.3.3

Cordova:

   Cordova CLI       : 10.0.0
   Cordova Platforms : android 9.0.0, ios 6.1.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 5.0.0, (and 27 other plugins)

Utility:

   cordova-res                          : 0.15.3
   native-run (update available: 1.3.0) : 1.2.2

System:

   ios-deploy : 1.9.4
   ios-sim    : 8.0.2
   NodeJS     : v15.11.0 (/usr/local/bin/node)
   npm        : 7.6.3
   OS         : macOS Big Sur
   Xcode      : Xcode 12.4 Build version 12D4e

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by vogloblinsky** [comment]
@sufian1985 it is related to this : https://github.com/apache/cordova-plugin-splashscreen/pull/263

**Comment by breautek** [comment]
iOS code has been removed from the cordova-plugin-splashscreen@6, because the code has been migrated to cordova-ios@6 as a core feature.

Older versions of this plugin however may still install on cordova-ios@6 which will cause conflict issues.

The solution is to ensure you're using the latest version cordova-plugin-splashscreen@6.

**Comment by awreese** [comment]
@breautek Sorry, can you clarify what the solution is here for this issue? We're currently using `cordova: ^10.0.0`, and `cordova-ios: ^6.3.0` and `cordova-plugin-splashscreen: ^6.0.2` and see the same issue with missing loading spinner on iOS.

**Comment by breautek** [comment]
> @breautek Sorry, can you clarify what the solution is here for this issue? We're currently using `cordova: ^10.0.0`, and `cordova-ios: ^6.3.0` and `cordova-plugin-splashscreen: ^6.0.2` and see the same issue with missing loading spinner on iOS.

If it's not working with splashscreen v6 installed (or removed) then I'd suggest raising an issue at the cordova-ios repo where the splashscreen is now implemented: https://github.com/apache/cordova-ios/issues

I'm not too familiar with iOS side of development but I suspect the spinner support was removed due to Apple's storyboard integration for launch screens which I think expects a static UI. At least I see lack of `spinner` terminology used in the codebase. If I'm right, then it means our documentation is unfortunately outdated, but someone with more experience than me might be able to provide better insight.

**Comment by erisu** [comment]
Spinner is no longer supported. https://github.com/apache/cordova-ios/issues/946#issuecomment-659485852
