### ISSUE TITLE
Splashscreen start with statusbar in Cordova 10

### ISSUE THREAD

**Issue by EFBergamo** [apache/cordova-plugin-splashscreen#309]
Splashscreen no fullscreen in app initialization.
Cordova version 10

**Comment by breautek** [comment]
Cordova isn't responsible on how to render splashscreens, it just takes what is passed in and package them for the OS to consume. If the splashscreen isn't rendering properly, it is most likely because you aren't following the proper resolution sizes.

Android: https://cordova.apache.org/docs/en/latest/reference/cordova-plugin-splashscreen/index.html#image-sizing-table
IOS: 
https://cordova.apache.org/docs/en/latest/reference/cordova-plugin-splashscreen/index.html#single-image-launch-screen
It's hard to give useful feedback because you decided to delete the questions asked in the issue form rather than fill them out.
