### ISSUE TITLE
Why black screen before splash screen and white screen after splash screen in android?

### ISSUE THREAD

**Issue by balaji-subramaniyam** [apache/cordova-plugin-splashscreen#322]
Hi team, I have facing this issue that once before the splash screen launches a **black screen** is presenting. And once after the splash screen launched a **white screen** is presenting. 
How to solve this issue?
Thanks in advance.

**Comment by phiasco12** [comment]
any update on this?

**Comment by phiasco12** [comment]
is this plugin abandoned?!

**Comment by breautek** [comment]
Question isn't totally clear.

Is the splashscreen shown at all or do you see black screen -> white screen?

Black screen would likely be the native background color.

A white screen generally means the app failed to load. Often due to a javascript error. Using chrome's web inspector will provide more insight if this is the case.

> is this plugin abandoned?!

Nope, but it is working towards being deprecated, and will become deprecated once the android codebase is migrated as part of the core platform (like the other supported platforms).

**Comment by fredriksthlm** [comment]
Try set this in your theme:
<item name="android:windowDisablePreview">true</item>

**Comment by jcesarmobile** [comment]
Closing because there is no enough information.
If the black screen is on Android 12 devices it’s because of https://github.com/apache/cordova-plugin-splashscreen/issues/311

**Comment by ptorrent** [comment]
Did you solve the case ?
