### ISSUE TITLE
Tried calling SplashScreen.hide, but the SplashScreen plugin is not installed on Android 12

### ISSUE THREAD

**Issue by hoatran2205** [apache/cordova-plugin-splashscreen#324]
# Bug Report
Tried calling SplashScreen.hide, but the SplashScreen plugin is not installed on Android 12
## Problem
SplashScreen show but didn't close when using a device with version Android 12
### What is expected to happen?
 Node : v10.21.0
cordova-android: v8.0.0
ionic-native/splash-screen: v5.0.0
Please guide me How to close SplashScreen after app init when using device is version Android 12

## Checklist

- [ ] I searched for existing GitHub issues
- [ ] I updated all Cordova tooling to most recent version
- [ ] I included all the necessary information above

**Comment by breautek** [comment]
`ionic-native/splash-screen` depends on `cordova-plugin-splashscreen`

Are you sure `cordova-plugin-splashscreen` is installed?

Note that Node 10 / cordova-android 8 is out of support. Any bugs or issues related to these versions will not be addressed. It's recommended to update to Node 14.x or 16.x and to cordova-android@10 as soon as it's feasible.

**Comment by hoatran2205** [comment]
@breautek I use the same config but when build app by

**Comment by breautek** [comment]
Installing my app on an Android 12 simulator doesn't produce this issue.

My app uses `.hide()` splashscreen API after it
1. Loads in the web app code,
2. Determines if there is saved user credentials
3. If there is saved user credentials, it validates it to ensure it is still valid
4. Loads either the Login Screen or the app's main screen. Once either these screens are fully loaded/rendered, only then the splashscreen is hidden.

I however don't use ionic. I just use the cordova API directly.

You may need to provide a sample reproduction app that demonstrates this issue without the use of ionic. If you can't reproduce your issue without using the ionic framework, then it may suggest that the issue is within the ionic framework rather than Cordova. If you can reproduce the issue without the use of ionic, then please do share the sample reproduction app which can be serve as a test case.

**Comment by ivinantony** [comment]
Android 12 has built in splash screen and now in the app showing 2 splashes on android 12. How to fix this issue

**Comment by jcesarmobile** [comment]
In other issue you mentioned you are using capacitor, this plugin is not compatible with capacitor, you have to use capacitor’s splash plugin instead

https://capacitorjs.com/docs/apis/splash-screen
