### ISSUE TITLE
Disable Splash Screen on reboot

### ISSUE THREAD

**Issue by jfoclpf** [apache/cordova-plugin-splashscreen#345]
Sometimes APP reboots on devices with low memory RAM, particularly using the Camera plugin.

I can recover the useful information with `document.addEventListener('resume')` but is it possible to deactivate Splash Screen on these circumstances, that is, show Splash Screen really just on the first start up?

I have `<preference name="SplashShowOnlyFirstTime" value="true" />` on config.xml but it doesn't work

**Comment by breautek** [comment]
`SplashShowOnlyFirstTime` is not a valid preference for this plugin, which only supports the `browser` platform now.

I believe `SplashShowOnlyFirstTime` used to be a preference, but now that Android has it's own splashscreen system, cordova-android uses that instead of crafting its own. Partly because Android's splashscreen will display regardless if you provide your own or not.

[Android's splashscreen](https://developer.android.com/develop/ui/views/launch/splash-screen) system will always be displayed in two situations:

>When a user launches an app while the app's process isn't running (a [cold start](https://developer.android.com/topic/performance/vitals/launch-time#cold)) or the Activity isn't created (a [warm start](https://developer.android.com/topic/performance/vitals/launch-time#warm)), the following events occur:
>
>The system shows the splash screen using themes and any animations that you define.
>
>When the app is ready, the splash screen is dismissed and the app displays.
>
>The splash screen never shows during a [hot start](https://developer.android.com/topic/performance/vitals/launch-time#hot).

Unfortunately when it comes to the camera, it may kill your app's activity, so when it returns to the app, it does what they call a warm start. And this is not something we can control.

**Comment by jfoclpf** [comment]
Thank you for the information
