### ISSUE TITLE
Plugin not supported in cordova-android: 13

### ISSUE THREAD

**Issue by pjdpaulsagnik** [apache/cordova-plugin-splashscreen#350]
# Bug Report

## Problem
Plugin not supported in cordova-android: 13

### Environment, Platform, Device

cordova-android
platform: android

**Comment by breautek** [comment]
It's intentional. The splashscreen implementation is part of the core platform as of cordova-android@11 which implements the android splashscreen feature.

If your project uses the browser platform, then you can upgrade the splashscreen plugin to 6.0.2 or later to prevent the splashscreen from attempting to install on the android platform, which will cause conflicts.

If your project also uses the iOS platform, upgrading the splashscreen plugin will also remove the iOS implementation as Cordova iOS platform also has the splashscreen implemented in the core platform now since cordova-ios@6. Therefore your project needs to be running at least version 6 of the Cordova iOS platform.

If your project is running at least cordova-android@11 and cordova-ios@6 and doesn't use the browser platform, then the splashscreen plugin can be uninstalled.

**Comment by pjdpaulsagnik** [comment]
@breautek , how to use splashscreen in applications with cordova-andoid: 13 for android devices ?

**Comment by breautek** [comment]
The splashscreen screen API is available by default without requiring the plugin. There is some slight difference, see https://cordova.apache.org/docs/en/latest/core/features/splashscreen/index.html for the current documentation.
